version: '2'
services:

  nginx:
    build:
      context: ./images/nginx
      args:
        - arg_host_uid=$HOST_UID
    ports:
      - "80:80"
    volumes_from:
      - app
    volumes:
      - "./config/nginx/conf.d:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
    links:
      - php


  mysql:
    image: mariadb:latest
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"

  php:
    build:
      context: ./images/php
      args:
        - arg_host_uid=$HOST_UID
    volumes_from:
      - app
    volumes:
      - "./log/php:/var/log/"
    links:
      - mysql

  composer:
    image: composer
    volumes:
      - "$APP_PATH:/app"
    command: "true"

  app:
    image: php:7.1-fpm
    command: "true"
    volumes:
      - "$APP_PATH:/var/www/app/"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD